# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlideTabKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlideTabKitDemo
  pod 'SnapKit', '~> 3.2.0'
  pod 'FrameKit', '~> 0.1.0'

  target 'SlideTabKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SlideTabKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
